# Generated by Django 3.0.7 on 2020-12-19 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('duration', models.IntegerField(choices=[(3, '3 - Months'), (6, '6 - Months'), (9, '9 - Months'), (12, '12 - Months')], default=3)),
                ('rate_of_interest', models.IntegerField(choices=[(5, '5% PA'), (10, '10% PA')], default=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
