# Generated by Django 3.0.7 on 2020-12-20 06:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userloan',
            name='date_applied',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
