# Generated by Django 3.0.7 on 2020-12-19 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='username',
            field=models.CharField(default='RootUser', max_length=150, unique=True),
            preserve_default=False,
        ),
    ]
